### ISSUE TITLE
Using TLS certificate for manage kafka

### ISSUE THREAD

**Issue by caiounderscore** [electric-saw/kafta#13]
Hi everyone, 

Firstly I'd like to congratulate the author for this project.

This is a question and not an issue.

Is it possible use TLS configuration for create topics for example? 
I read documentation and very quickly the source code, but i didn't see an example or implementation.

**Comment by lucasviecelli** [comment]
Hello, thanks for this issue.

I haven't tried using kaftan with TLS and I don't think it will work. Perhaps it is an excellent contribution that we can implement in the future

**Comment by ecoupal-believe** [comment]
My 2 cents

https://github.com/electric-saw/kafta/pull/16
