### ISSUE TITLE
Kafta isn`t working on mac intel

### ISSUE THREAD

**Issue by bgvit** [electric-saw/kafta#23]
I have installed kafta following this command:

`go install  github.com/electric-saw/kafta/cmd/kafta@latest`

However, I restarted the shell and tried to use kafta but:

`zsh: command not found: kafta`

What would be?

**Comment by snakeice** [comment]
Please check if your `$(go env GOPATH)/bin` it's in your $PATH

**Comment by bgvit** [comment]
I think you're right. I have this about go on my $PATH: `PATH=/Users/fulano/.gobrew/current/bin:/Users/fulano/.gobrew/bin`

However, if I type the command that you suggested I have this output:

```
$(go env GOPATH)/bin
zsh: no such file or directory: /Users/fulano/go/bin
```

```
go env GOPATH
/Users/fulano/go
```

I don`t understand yet how will I solve this problem, but I'll search. If u know something about it, please let me know. 
Thank you so much

**Comment by snakeice** [comment]
try export PATH="/Users/fulano/go/bin:$PATH"
